//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattlePets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattlePet
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> hp { get; set; }
        public Nullable<int> dmg { get; set; }
        public Nullable<int> speed { get; set; }
    }
}
